# Generated by Django 6.0.3 on 2026-03-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="reset_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="reset_code_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
