# Generated by Django 6.0.3 on 2026-04-02 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the clinical note', max_length=200)),
                ('content', models.TextField(help_text='Detailed content of the clinical note')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for organizing notes', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(help_text='Doctor who wrote this note', limit_choices_to={'role': 'medecin'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_notes', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(help_text='Patient this note is about', limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', '-created_at'], name='note_note_patient_58e023_idx'), models.Index(fields=['doctor', '-created_at'], name='note_note_doctor__a0c7fb_idx'), models.Index(fields=['created_at'], name='note_note_created_b8c33e_idx')],
            },
        ),
    ]
