# Generated by Django 6.0.3 on 2026-03-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sleepsession',
            name='quality',
        ),
        migrations.AddField(
            model_name='sleepsession',
            name='actual_sleep_hours',
            field=models.FloatField(blank=True, help_text='Heures de sommeil réel', null=True),
        ),
        migrations.AddField(
            model_name='sleepsession',
            name='apnea_count',
            field=models.IntegerField(default=0, help_text="Nombre d'apnées"),
        ),
        migrations.AddField(
            model_name='sleepsession',
            name='efficiency',
            field=models.FloatField(blank=True, help_text='Efficacité du sommeil (%)', null=True),
        ),
        migrations.AddField(
            model_name='sleepsession',
            name='hypopnea_count',
            field=models.IntegerField(default=0, help_text="Nombre d'hypopnées"),
        ),
        migrations.AddField(
            model_name='sleepsession',
            name='status',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sleepsession',
            name='ahi',
            field=models.FloatField(blank=True, help_text='Index Apnée-Hypopnée', null=True),
        ),
        migrations.AlterField(
            model_name='sleepsession',
            name='duration_hours',
            field=models.FloatField(blank=True, help_text='Temps total au lit (heures)', null=True),
        ),
    ]
