# Generated by Django 6.0.3 on 2026-03-30 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
