# Generated by Django 6.0.3 on 2026-05-31 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=64, unique=True)),
                ("patient_name", models.CharField(blank=True, max_length=128)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="SensorReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ppg_value", models.FloatField(help_text="Raw PPG amplitude")),
                (
                    "spo2",
                    models.FloatField(blank=True, help_text="SpO2 in %", null=True),
                ),
                (
                    "heart_rate",
                    models.FloatField(blank=True, help_text="BPM", null=True),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="statistique.device",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "timestamp"],
                        name="statistique_device__73ef3b_idx",
                    )
                ],
            },
        ),
    ]
