# Generated by Django 6.0.3 on 2026-05-31 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statistique", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SleepSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("avg_spo2", models.FloatField(blank=True, null=True)),
                ("avg_ppg", models.FloatField(blank=True, null=True)),
                ("avg_hr", models.FloatField(blank=True, null=True)),
                ("min_spo2", models.FloatField(blank=True, null=True)),
                ("total_readings", models.IntegerField(default=0)),
                ("apnea_detected", models.BooleanField(blank=True, null=True)),
                ("ahi_score", models.FloatField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="statistique.device",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddField(
            model_name="sensorreading",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="readings",
                to="statistique.sleepsession",
            ),
        ),
    ]
